import {
  Button,
  Input,
  Flex,
  Center,
  SimpleGrid,
  Container,
  Image,
  Box,
} from "@chakra-ui/react";
import Head from "next/head";
import { useState } from "react";
import Nav from "../components/Navbar";
import api from "./api/main";

export default function Home() {
  const [url, setUrl] = useState("");
  const [dataPage, setDataPage] = useState([]);

  const fetchData = () => {
    if (!url) {
      return;
    }
    api
      .post("/instagramData", {
        body: url,
        headers: { "Content-Type": "application/json" },
      })
      .then((res) => {
        setDataPage(res.data.result);
        setUrl("")
      })
      .catch((err) => {
        console.log(err);
      });
  };

  const downloadImage = (url: string, name: string) => {
    fetch(url)
      .then((resp) => resp.blob())
      .then((blob) => {
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.style.display = "none";
        a.href = url;
        a.download = name;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
      })
      .catch(() => alert("An error sorry"));
  };

  return (
    <div>
      <Head>
        <title>Instagram - Tools</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <Container maxW="1000px">
        <Center gap={2} mt={5}>
          <Input
            value={url}
            placeholder="Adicione a URL da imagem aqui ou link do perfil"
            onChange={(e) => setUrl(e.target.value)}
          />
          <Button variant={"solid"} onClick={fetchData}>
            Buscar
          </Button>
        </Center>
        <Center mt={50} flexDirection="column" gap={2}>
          {dataPage ? (
            <SimpleGrid columns={{ base: 1, md: 4 }} spacing={10} mb={10}>
              {dataPage?.map((item: string, i: number) => (
                <Box key={i}>
                  <Flex direction="column">
                    <Image
                      borderTopEndRadius={"md"}
                      borderTopStartRadius={"md"}
                      crossOrigin="anonymous"
                      src={`https://cors-anywhere.herokuapp.com/${item}`}
                      width={400}
                    />
                    <Button
                      borderTopEndRadius={0}
                      borderTopStartRadius={0}
                      onClick={() =>
                        downloadImage(
                          `https://cors-anywhere.herokuapp.com/${item}`,
                          `media.png`
                        )
                      }
                    >
                      Baixar imagem
                    </Button>
                  </Flex>
                </Box>
              ))}
            </SimpleGrid>
          ) : null}
        </Center>
      </Container>
    </div>
  );
}
